<a href="https://colab.research.google.com/github/djeannie29/cafe_dados_e_gatos/blob/main/pandas/notebooks/01_csv_separador_sep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p align="center">
  <img src="https://raw.githubusercontent.com/djeannie29/cafe_dados_e_gatos/main/pandas/notebooks/banner_novo_notebooks.png" width="900" alt="Café com Dados & Gatos">
</p>

# SHORT 01 — Separador ; vs , (vira 1 coluna só)
Arquivo: `pandas/data/bugs_excel_1000_utf8sig.csv`

Colunas usadas: preco, peso_kg, data_compra, id_cliente, cep

In [21]:
from pathlib import Path

if not Path("cafe_dados_e_gatos").exists():
    !git clone https://github.com/djeannie29/cafe_dados_e_gatos.git

%cd cafe_dados_e_gatos

Cloning into 'cafe_dados_e_gatos'...
remote: Enumerating objects: 259, done.
remote: Counting objects: 100% (137/137), done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 259 (delta 86), reused 21 (delta 21), pack-reused 122 (from 1)
Receiving objects: 100% (259/259), 19.48 MiB | 30.09 MiB/s, done.
Resolving deltas: 100% (128/128), done.
/content/cafe_dados_e_gatos/cafe_dados_e_gatos/cafe_dados_e_gatos/cafe_dados_e_gatos/cafe_dados_e_gatos/cafe_dados_e_gatos/cafe_dados_e_gatos

In [22]:
import pandas as pd

arq = Path("pandas") / "data" / "bugs_excel_1000_utf8sig.csv"

In [29]:
df_errado = pd.read_csv(arq)
print(df_errado.shape)
print(df_errado.columns)
df_errado.head()

(1000, 1)
Index(['id;id_cliente;nome;cidade;cep;preco;peso_kg;data_compra;obs;idade_anos'], dtype='object')

                                                                        id;id_cliente;nome;cidade;cep;preco;peso_kg;data_compra;obs;idade_anos
1;670487;Fábio Pereira;Porto Alegre;52579931;298  76;3                                  411;12/02/2026;ação necessária;102
2;116739;Bárbara Souza;Curitiba;39666982;54       95;;23/12/2025;ok;179                                                NaN
3;026225;Júlia Silva;Goiânia;86727439;853         53;10                                     201;05/08/2025;café + dados;92
4;777572;Júlia Silva;Campinas;07324144;138        09;10                                             750;18/10/2025;válido;
5;288389;María Pereira;Foz do Iguaçu;32123815;200 90;3                                170;05/05/2024;pendência: e-mail;106

In [28]:
df_certo = pd.read_csv(arq, sep=";")
print(df_certo.shape)
print(df_certo.columns)
df_certo.head()

(1000, 10)
Index(['id', 'id_cliente', 'nome', 'cidade', 'cep', 'preco', 'peso_kg',
       'data_compra', 'obs', 'idade_anos'],
      dtype='object')

,id,id_cliente,nome,cidade,cep,preco,peso_kg,data_compra,obs,idade_anos
0,1,670487,Fábio Pereira,Porto Alegre,52579931,"298,76","3,411",12/02/2026,ação necessária,102.0
1,2,116739,Bárbara Souza,Curitiba,39666982,"54,95",NaN,23/12/2025,ok,179.0
2,3,26225,Júlia Silva,Goiânia,86727439,"853,53","10,201",05/08/2025,café + dados,92.0
3,4,777572,Júlia Silva,Campinas,7324144,"138,09","10,750",18/10/2025,válido,NaN
4,5,288389,María Pereira,Foz do Iguaçu,32123815,"200,90","3,170",05/05/2024,pendência: e-mail,106.0